# Generated by Django 3.1.1 on 2020-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('image', models.ImageField(default='NoPhoto', upload_to='customer/')),
            ],
            options={
                'verbose_name': 'Наша команда',
                'verbose_name_plural': 'Наши команды',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='ContactClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=22, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Контакт клиента',
                'verbose_name_plural': 'Контакты клиентов',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='NoPhoto', upload_to='customer/', verbose_name='Фото')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наши работы')),
                ('image', models.ImageField(default='NoPhoto', upload_to='portfolio/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Наша работа',
                'verbose_name_plural': 'Наши работы',
                'ordering': ('-title',),
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Прайс')),
                ('image', models.ImageField(default='NoPhoto', upload_to='price/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Прайс',
                'verbose_name_plural': 'Прайсы',
                'ordering': ('-title',),
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Производство')),
                ('image', models.ImageField(default='NoPhoto', upload_to='production/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Производство',
                'verbose_name_plural': 'Производствы',
                'ordering': ('-title',),
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наши услуги')),
                ('image', models.ImageField(default='NoPhoto', upload_to='services/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Наша услуга',
                'verbose_name_plural': 'Наши услуги',
                'ordering': ('-title',),
            },
        ),
    ]
