# Generated by Django 3.1.1 on 2020-09-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ('name',), 'verbose_name': 'Наша команда', 'verbose_name_plural': 'Наши команды'},
        ),
        migrations.AlterModelOptions(
            name='contactclient',
            options={'ordering': ('name',), 'verbose_name': 'Контакт клиента', 'verbose_name_plural': 'Контакты клиентов'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('name',), 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ('title',), 'verbose_name': 'Наша работа', 'verbose_name_plural': 'Наши работы'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('title',), 'verbose_name': 'Прайс', 'verbose_name_plural': 'Прайсы'},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ('name',), 'verbose_name': 'Производство', 'verbose_name_plural': 'Производства'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ('title',), 'verbose_name': 'Наша услуга', 'verbose_name_plural': 'Наши услуги'},
        ),
        migrations.RenameField(
            model_name='production',
            old_name='title',
            new_name='name',
        ),
    ]
